<?php

namespace Database\Seeders;

use App\Models\User;
use DateTime;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DepartmentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $departments = [
            'Auditoria Interna',
            'Biblioteca Central',
            'Campus Dr. Leonel Miranda(Goytacazes)',
            'CASTE - CASA AGRICULTURA, SUST. TERRITÓRIO E EDUCAÇÃO',
            'CORIN',
            'CPPD/Comissão Permanente de Pessoal Docente',
            'CTUR = Colégio Técnico da Univ. Rural',
            'DGV = Divisão de Guarda e Vigilância',
            'DGV Monitoramento Vídeo',
            'Extintores',
            'IA = Instituto de Agronomia/Diretoria',
            'IA/Dep. de Agrotecnologia e Sustentabilidade',
            'IA/DF = Dep. de Fitotecnia',
            'IA/DS = Dep. de Solos',
            'IA/PPGA-CS/Pos Graduação em Ciência do Solo',
            'IA/PPGAO/Pos Graduação em Agricultura Orgânica',
            'IA/PPGEA = Programa de Pós-Graduação em Educação Agrícola',
            'IA/PPGF/Pos Graduação em Fitotecnia',
            'ICBS/Centro Integrado de Manejo de Pragas',
            'ICBS/DAAH - Depart. Anatom. Animal e Humana',
            'ICBS/DB = Dep. de Botânica',
            'ICBS/DBA/Biologia = Departamento de Biologia Animal',
            'ICBS/DBA/Histologia e Embriologia = Departamento de Biologia Animal',
            'ICBS/DBA/Zoologia = Departamento de Biologia Animal',
            'ICBS/DCFAR/SICS - Dep.de Ciências Farmacêuticas',
            'ICBS/DCFis = Dep. Ciênc. Fisiológicas',
            'ICBS/DENF = Departamento de Entomologia e Fitopatologia',
            'ICBS/DG = Dep. de Genética',
            'ICBS/DIRETORIA/Inst. Cienc. Biolog. e da Saude',
            'ICBS/PPGFBA - Fitossanidade e Biotecnologia Aplicada',
            'ICE = Inst. de Ciênc. Exatas/Diretoria',
            'ICE/DECOMP = Dep. de Computação',
            'ICE/DEFIS = Dep. de Física / P-1',
            'ICE/DEFIS = Dep. de Física / PAP 01',
            'ICE/DEFIS = Dep. de Física / PAP 02',
            'ICE/DEMAT = Dep. de Matemática / P-1',
            'ICE/DEMAT = Dep. de Matemática / Pythagoras',
            'ICE/Pavilhão de Aulas Práticas',
            'ICHS/DDAS/CPDA/ Departamento de Desenvolv Agricult Sociedade',
            'ICHS/Depart Ciências Sociais/PPGCS',
            'ICHS/Departamento de Artes',
            'ICHS/Departamento de Ciencias Jurídicas',
            'ICHS/Departamento de Ciências Sociais',
            'ICHS/Departamento de Filosofia',
            'ICHS/Departamento de História',
            'ICHS/Departamento de História/Pós Graduação PPHR',
            'ICHS/Departamento de Jornalismo',
            'ICHS/DLC = Departamento de Letras e Comunicação',
            'ICHS/DLC/ISF = Inglês Sem Fronteiras',
            'ICHS/DLC/PAP Jornalismo Comunicação',
            'ICHS/DLC/PET = PET Letras',
            'ICHS/DLC/PROF Letras',
            'ICHS/Graduação em Relações Internacionais',
            'ICHS/Instituto, Diretoria e Secretaria',
            'ICHS/Pós Graduação em Filosofia',
            'ICSA/CEDERJ',
            'ICSA/DCCF = Departamento de Ciências Contábeis Finanças',
            'ICSA/Departamento de Adm Pública',
            'ICSA/Departamento de Ciências Administrativas',
            'ICSA/Departamento de Ciências Econômicas',
            'ICSA/Departamento Econ Domést Hotelaria',
            'ICSA/Diretoria',
            'ICSA/Hotel Universitário',
            'ICSA/PPGDT',
            'ICSA/PPGE - Programa Pós Graduação Estratégia',
            'IE/DECMS = Departamento de Educ. Campo Movimentos Sociais',
            'IE/DEFD = Departamento de Educ. Fís. e Desportos',
            'IE/DEPSI - Departamento de Psicologia',
            'IE/DTPE - Departamento de Teoria e Planej. de Ensino',
            'IE/Instituto de Educação, Diretoria, Secretaria',
            'IF = Inst. de Florestas/Diretoria',
            'IF/CCGEF = Coord. Curso Graduação Eng Florestal',
            'IF/DCA = Dep. de Ciências Ambientais',
            'IF/DPF = Dep. de Prod. Florestais',
            'IF/DS = Dep. de Silvicultura',
            'IF/PPGCAF = Prog Pós-Grad Ciências Ambientais e Florestais',
            'IF/PPGPDS = Prog Pós-Grad Práticas Desenvolv Sustentável',
            'IGEO / DGG = Depart. de Geografia',
            'IGEO / Instituto de Geociências',
            'IGEO/ Depart. de Petrologia e Geotectônica',
            'IGEO/DGEO = Dep. de Geociências',
            'IM / CLOG = Coordenação de logística',
            'IM / RU = Restaurante Universitário',
            'IM =Campus de Nova Iguaçu',
            'IM/Biblioteca do Instituto Multidisciplinar',
            'IM/COMAC=Cood. de materiais, Aquisição e Contrato',
            'IM/COTIC',
            'IM/DAT = Departamento de Administração e Turismo',
            'IM/DCC = Dep. de Ciências da Computação',
            'IM/DCJUR = Departamento de Ciências Jurídicas',
            'IM/DEGEO = Departamento de Geografia',
            'IM/DES = Departamento de Educação e Sociedade',
            'IM/DHE = Departamento de História e Economia',
            'IM/DIRIM = Direção do IM',
            'IM/DL = Departamento de Letras',
            'IM/DTL = Departamento De Tecnologia e Linguagens.',
            'IM/SIIM = Superintendência de Informática do Instituto Multidisciplinar',
            'IQ / INSTITUTO DE QUÍMICA = Direção',
            'IQ/DB = Departamento de Bioquímica',
            'IQ/Dep. de Quimica Analitica',
            'IQ/DEQUIM = Dep. de Química',
            'IQ/DQF = Departamento de Química Fundamental',
            'IQ/DQO = Departamento de Química Orgânica',
            'IQ/PPGQ/Central Analítica Multiusuário',
            'IT/ Inst. de Tecnologia/Diretoria',
            'IT/DAU = Dep. de Arquit. e Urbanismo',
            'IT/DEng. = Dep. de Engenharia',
            'IT/Departamento Engenharia Agrícola e Ambiental',
            'IT/DEQ / Laboratório de Nano Tecnologia',
            'IT/DEQ = Dep. de Eng. Química',
            'IT/DTA = Dep. de Tecnologia de Alimentos',
            'ITR = Instituto Três Rios',
            'ITR/DCAA = Dep. de Ciências Adm. e do Ambiente',
            'ITR/DCEE= Dep. de Ciências Econôm. e Exatas',
            'ITR/DCMA=Departamento de Ciênciais do Meio Ambiente',
            'ITR/DDHL=Departamento de Direito, Humanas e Letras',
            'IV = Instituto de Veterinária/Secretaria',
            'IV/DESP = Dep. de Epidemiologia e Saúde Pública',
            'IV/DMCV = Dep. de Med. e Cirurgia Vet.',
            'IV/DMIV = Dep. de Microb. e Imunol. Vet.',
            'IV/DPA = Dep. de Parasitologia Animal',
            'IV/HV = Hospital Veterinário',
            'IZ /EBM = Estação de Bio. Marinha',
            'IZ = Instituto de Zootecnia/Diretoria',
            'IZ/DNAP = Dep. de Nutrição Animal e Pastagens',
            'IZ/DPA = Dep. de Produção Animal',
            'IZ/DRAA = Dep. de Reprod. e Aval. Animal',
            'IZ/Posto de Aquicultura',
            'Museu de Solos do Brasil',
            'NAI/NÚCLEO DE ACESSIBILIDADE E INCLUSÃO DA UFRRJ',
            'PROAES / LGBT',
            'PROAES = PRO-REITORIA DE ASSUNTOS ESTUDANTIS',
            'PROAES/DGSAE = Divisão de Gestão de Suprimentos de Assistência Estudantil',
            'PROAES/DIMAE = Divisão Multidisciplinar de Assistência ao Estudante',
            'PROAES/SERE = Setor de Residência Estudantil',
            'PROAES/SRU = Setor dos Restaurantes Universitários',
            'PROAF / DMSA / CLOG - Coord. Logistica',
            'PROAF /DCF = Dep. de Contabilidade e Finanças',
            'PROAF /DMSA',
            'PROAF /Lavanderia',
            'PROAF = PRO-REITORIA DE ASSUNTOS FINANCEIROS',
            'PROAF/Departamento de Contrato e Gestão de Espaços Físicos',
            'PROAF/DMSA/CADMIN = Coordenação de Administração',
            'PROAF/DMSA/CPACS = Coord Planej Acompanh Compras Serv',
            'PROAF/DPSA = Divisão de Patrimônio e Serv. Auxiliares',
            'PROEXT / Gustavão',
            'PROEXT / Hilton Salles',
            'PROEXT / Pré Enem - Antigo C. Memória',
            'PROEXT / Salão Azul',
            'PROEXT = PRO-REITORIA DE EXTENSÃO',
            'PROEXT/CAC = Centro de arte e cultura',
            'PROEXT/DEPTº DE ESPORTE E LAZER',
            'PROEXT/Escola de Extensão',
            'PROGEP / CASST = Saúde do Trabalhador',
            'PROGEP = Pro Reitoria de Gestão de Pessoas',
            'PROGEP/CDPNR - Coord Distrib Próprio Nacional Resid',
            'PROGEP/CODEP = Coord. de Desenv. de Pessoas',
            'PROGEP/DP DAGP = Depart Administr Gestão Pessoas',
            'PROGEP/NASSUR',
            'PROGER = Procuradoria Geral',
            'PROGRAD = PRO-REITORIA DE ENSINO E GRADUAÇÃO',
            'PROGRAD/DEST = Divisão de Estágios',
            'PROGRAD/PAT',
            'PROPLADI/CODIN = Coordenadoria de Desenvolvimento Institucional',
            'PROPLADI/COPEA',
            'PROPLADI/COTIC - Coord Tecnolog Inform Comunic',
            'PROPLADI/COTIC - Switchs e outros',
            'PROPLADI/Núcleo TRatamento de Dados INstitucionais',
            'PROPLADI/PRO-REITORIA DE PLANEJAMENTO E DES.INST.',
            'PROPLADI/SAPG = Seção de Arquivo e Protocolo Geral',
            'PROPPG / Casa de Hóspedes',
            'PROPPG / NIT = Núcleo Inovaçõo Tecnológica',
            'PROPPG = PRO-REITORIA DE PESQUISA E PÓS-GRADUAÇÃO',
            'PROPPG/COPESQ = Coord. de Pesquisa',
            'PROPPG/EDITORA',
            'PROPPG/JB = Jardim Botânico da UFRRJ',
            'PU = Prefeitura Universitária',
            'PU/Divisão de Parques e Jardins',
            'PU/Divisão de Saúde',
            'PU/DSG = Divisão de Serviços Gerais',
            'Reitoria / Casa do Reitor',
            'Reitoria / COPIEPE - IZ/FAIZ - Fazenda = Coord. Esp. de Prod. Integ. ao Ensino, Pesq. e Ext.',
            'Reitoria /Coord Comunicação Social Jornalismo',
            'REITORIA/ VICE-REITORIA',
            'Reitoria/CEAD = Coordenadoria de Educaçao da Distância',
            'Reitoria/Comissão P.Inst.pela Diversidade, Gênero e Etnia Ração e Inclusão',
            'REITORIA/CPA - Comiss Permanente Avaliação',
            'Reitoria/Gabinete/secretaria',
            'reitoria/ouvidoria',
            'RURAL',
            'SOC = Secretaria dos Órgãos Colegiados',
            'VEÍCULOS',
        ];

        $user = (User::first())->id;
        if ($user) {
            foreach ($departments as $department) {
                DB::table('departments')->insert([
                    'name' => $department,
                    'user_id'  =>  $user,
                    'created_at' => new DateTime('now'),
                ]);
            }
        }
    }
}
